services:
  mysql:
    image: mariadb:11.6
    hostname: mysql
    container_name: mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: slurm_acct_db
      MARIADB_USER: slurm
      MARIADB_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      - slurm-network

  slurmdbd:
    build: .
    image: shared-slurm:latest
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    networks:
      - slurm-network

  slurmctld:
    image: shared-slurm:latest
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    networks:
      - slurm-network

  c1:
    image: shared-slurm:latest
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

  c2:
    image: shared-slurm:latest
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:

networks:
  slurm-network:
    driver: bridge
